### ISSUE TITLE
＠web160
193134173+web005@users.noreply.github.com

### ISSUE THREAD

**Issue by web160** [web005/web#4]

**Comment by web005** [comment]
https://github.com/skills/introduction-to-github.git
-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEZl7HXBYJKwYBBAHaRw8BAQdAFgszTYh8q93yevtquwnVHEG0AR0M+BAwpHuD
YstV3Se0Gnpvb20zNyA8em9vbTM3QG91dGxvb2suanA+iHIEExYIABoECwkIBwIV
CAIWAQIZAQWCZl7HXAKeAQKbAwAKCRAWPhJhBpcIYU4mAP956LWMSJkNzupw/VVE
wfQ751V+J46nt+4YhQq76RC1zQD+OqOod1MUixXlS52xli4f7xk0LbduEXtGZRwM
K64zhwe4OARmXsdcEgorBgEEAZdVAQUBAQdAG345ab1Ch0imjgTTT9F5jEPFQAeN
/mRipXYXhsWpiHIDAQgHiGEEGBYIAAkFgmZex1wCmwwACgkQFj4SYQaXCGHpdAD/
WwHU2YwRzIqxqA+yvN2bH2qapdBylfCm1clh2qDqTGsA/Rfth1/uGedbvyCBh316
O1JDfTejDb0c2Ok7sJ2bgpUE
=Sbgo
-----END PGP PUBLIC KEY BLOCK-----
